import type { TripOption } from './types.ts';

const TRIP_OPTIONS: TripOption[] = [
  {
    tripId: 'TR-PAR-001',
    destination: 'Paris',
    country: 'France',
    origin: 'London',
    airline: 'Air France',
    flightNumber: 'AF1682',
    hotel: 'Hôtel Plaza Athénée',
    hotelRating: 5,
    departureDate: '2026-11-14',
    returnDate: '2026-11-21',
    nights: 7,
    passengers: 2,
    pricePerPerson: 920,
    totalPrice: 1840,
    currency: 'EUR',
    includes: ['Return flights', '7 nights hotel', 'Breakfast daily', 'Airport transfers'],
    dealTag: 'Best value',
  },
  {
    tripId: 'TR-PAR-002',
    destination: 'Paris',
    country: 'France',
    origin: 'London',
    airline: 'Eurostar',
    flightNumber: 'ES9016',
    hotel: 'Hotel Du Louvre',
    hotelRating: 4,
    departureDate: '2026-11-14',
    returnDate: '2026-11-21',
    nights: 7,
    passengers: 2,
    pricePerPerson: 680,
    totalPrice: 1360,
    currency: 'EUR',
    includes: ['Return Eurostar tickets', '7 nights hotel', 'Airport transfers'],
    dealTag: 'Budget pick',
  },
  {
    tripId: 'TR-PAR-003',
    destination: 'Paris',
    country: 'France',
    origin: 'London',
    airline: 'British Airways',
    flightNumber: 'BA308',
    hotel: 'Le Meurice',
    hotelRating: 5,
    departureDate: '2026-11-14',
    returnDate: '2026-11-21',
    nights: 7,
    passengers: 2,
    pricePerPerson: 1460,
    totalPrice: 2920,
    currency: 'EUR',
    includes: ['Business class flights', '7 nights luxury hotel', 'Breakfast & dinner', 'Concierge service'],
    dealTag: 'Luxury',
  },
];

export function findTripOption(tripId: string): TripOption | undefined {
  return TRIP_OPTIONS.find((trip) => trip.tripId === tripId);
}
